name: Check-BOEM-WEAS

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          install.packages(c("httr", "here", "lubridate"))
        shell: Rscript {0}      
        
      - name: Check if BOEM WEAs were updated recently
        run: |
          source(here::here("data-raw/updated_boem_weas.R"))
        shell: Rscript {0}